creating-initial-content
fhdsl/AI_for_software pull request #15
Opened 2023-04-10 15:01 UTC by ehumph

This PR adds the course content for the chapter on using AI to understand other people's code.

2023-04-12 18:06 UTC, avahoffman requested changes
Loving working through this!

A few overall notes:
- [ ] We should try to be consistent with the screenshot size in the google slides. As a general rule of thumb, I try to fill most of the slide while leaving a bit of whitespace. Sometimes this requires adjusting my window size (see below). Otherwise, the whitespace is inconsistent in the rendered version.
- [ ] Would it be worthwhile to add some ambiguous code, with the point being that more code can be helpful to the chatbot? I'm thinking about something like `my_string = "hello world"`, which could be either python or R. Other edge cases we should think about?
- [ ] How will folks evaluate themselves on the hands-on exercise? A link to answers? Do we intend to make actual quiz format quizzes to be compatible w/ leanpub and coursera?

![image](https://user-images.githubusercontent.com/15618412/231544707-ab25b099-37bf-4c71-a51c-f62397e2426a.png)

2023-04-12 18:12 UTC, ehumph commented
Also, adding an edge case is a great idea! My biggest worry with the examples is that they aren't very useful illustrations of what AI can do, but I am limited in my imagination of how to ask AI to create the code.

2023-04-12 18:14 UTC, ehumph commented on 06-understanding_other_ppl_code.Rmd
> +A good first step when facing unknown code is to find out what language it's in. You may already recognize it, but if you don't, AI can help.
Ooops, wrong screenshot

2023-04-12 18:15 UTC, ehumph commented on 06-understanding_other_ppl_code.Rmd
> +You can always ask for clarification if you need more information.
@avahoffman Do you think we should create a special ethics callout box as well, or is the "reflection" box fine?

2023-04-12 18:36 UTC, avahoffman commented on 06-understanding_other_ppl_code.Rmd
> +You can always ask for clarification if you need more information.
We have one :)

Just use

```
:::{.ethics}
```

I'm creating a `query` one right now as well

2023-04-12 18:55 UTC, ehumph commented on 06-understanding_other_ppl_code.Rmd
> +You can always ask for clarification if you need more information.
Awesome!

2023-04-12 21:05 UTC, ehumph commented on 06-understanding_other_ppl_code.Rmd
> +For the next two sections, we'll use Google's AI chatbot Bard. As always, feel free to use your favorite chatbot - all of them can provide help!
Done!

2023-04-12 21:06 UTC, ehumph commented on 06-understanding_other_ppl_code.Rmd
> +
Not really. I will edit that out when fixing the figures

2023-04-14 03:50 UTC, ehumph commented
Still too many words.

2023-04-14 15:47 UTC, avahoffman commented on 06-understanding_other_ppl_code.Rmd
> +_"It's like having a paired programmer explain things to you." ~dinosaur cartoon saying Howard's quote?_
```suggestion
> _"It's like having a paired programmer explain things to you." ~dinosaur cartoon saying Howard's quote?_
```

Using the carrot creates a quote box IIRC

2023-04-14 15:48 UTC, avahoffman commented on 06-understanding_other_ppl_code.Rmd
> +Reading unfamiliar code is like exploring an unfamiliar city without a map or a guide. Just like in a new city, you may not know where to start or how to navigate the codebase. You may encounter unfa
love it!!

2023-04-14 17:58 UTC, ehumph commented on 06-understanding_other_ppl_code.Rmd
> +Reading unfamiliar code is like exploring an unfamiliar city without a map or a guide. Just like in a new city, you may not know where to start or how to navigate the codebase. You may encounter unfa
I think Bard came up with that analogy.

2023-04-14 18:00 UTC, ehumph commented on 06-understanding_other_ppl_code.Rmd
>  ```
Mostly I was being lazy. Part of me thought it wasn't important for the code to be evaluated, since we're just asking questions about it, but I think for form's sake I should add in the {r}

2023-04-14 18:01 UTC, ehumph commented on 06-understanding_other_ppl_code.Rmd
> +_"It's like having a paired programmer explain things to you." ~dinosaur cartoon saying Howard's quote?_
Oh, good to know! Howard said it when I showed him how to use chatgpt for understanding the mario code and it was just a perfect description. I want to use it somehow, but I'm not sure the best way yet. I had a vague idea of having a cartoon avatar or mascot saying it, maybe? It would break up the wall of text too.

2023-04-14 18:04 UTC, avahoffman commented on 06-understanding_other_ppl_code.Rmd
> +_"It's like having a paired programmer explain things to you." ~dinosaur cartoon saying Howard's quote?_
We could use the dino!

2023-04-14 18:05 UTC, avahoffman commented on 06-understanding_other_ppl_code.Rmd
>  ```
Maybe it's more important for me, because I'm trying to show that the answer's not really changing

2023-04-14 18:17 UTC, merged